### open-source-startup

title: Open Source Startup

permalink: /:title

baseurl: ""

exclude:
- README.md

theme: jekyll-theme-cayman

description: Course page for the Open Source Startup Entrepreneurship 101 Course
